# Generated by Django 5.2.13 on 2026-05-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('resume_text', models.TextField()),
                ('ai_feedback', models.TextField()),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
